import{a as w,S as v,i as p}from"./assets/vendor-DMjJPMAs.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const i of t)if(i.type==="childList")for(const n of i.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&r(n)}).observe(document,{childList:!0,subtree:!0});function s(t){const i={};return t.integrity&&(i.integrity=t.integrity),t.referrerPolicy&&(i.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?i.credentials="include":t.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function r(t){if(t.ep)return;t.ep=!0;const i=s(t);fetch(t.href,i)}})();const S="49351008-1bfee9cf32a9c846c40651839",E="https://pixabay.com/api/";async function g(e,o=1){const s={key:S,q:e,image_type:"photo",orientation:"horizontal",page:o,per_page:15,safesearch:!0},r=await w.get(E,{params:s});if(!r.data.hits.length)throw new Error("No images found");return{images:r.data.hits,totalHits:r.data.totalHits}}let c;function h(e,o){o.innerHTML="";const s=e.map(q).join("");o.insertAdjacentHTML("beforeend",s),P(),setTimeout(()=>{o.querySelectorAll(".gallery-item").forEach(t=>t.classList.add("visible"))},50)}function q({webformatURL:e,largeImageURL:o,tags:s,likes:r,views:t,comments:i,downloads:n}){return`
    <li class="gallery-item">
      <a href="${o}">
        <img src="${e}" alt="${s}" loading="lazy" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes</b>${r}</p>
        <p class="info-item"><b>Views</b>${t}</p>
        <p class="info-item"><b>Comments</b>${i}</p>
        <p class="info-item"><b>Downloads</b>${n}</p>
      </div>
    </li>
  `}function P(){c==null||c.refresh(),c=new v(".gallery a",{captionsData:"alt",captionDelay:250})}const T=document.querySelector(".form"),u=document.querySelector(".gallery"),y=document.querySelector(".loader"),l=document.querySelector(".load-more"),L=document.querySelector(".end-message");let a=1,f="";const H=15;window.addEventListener("load",()=>{y.style.display="none"});function d(e){y.style.display=e?"block":"none"}T.addEventListener("submit",async e=>{e.preventDefault();const o=e.target.elements["search-text"],s=o.value.trim();if(!s){O("Please enter a search query!");return}M(),f=s;try{d(!0);const{images:r,totalHits:t}=await g(f,a);if(!r.length){m("No images found");return}h(r,u),b(t)}catch(r){m(r.message)}finally{d(!1),o.value=""}});l.addEventListener("click",async()=>{a++,l.classList.add("hidden"),d(!0);try{const{images:e,totalHits:o}=await g(f,a);setTimeout(()=>{h(e,u),$(),b(o)},500)}catch(e){m(e.message)}finally{setTimeout(()=>{d(!1)},500)}});function M(){a=1,u.innerHTML="",l.classList.add("hidden"),L.classList.add("hidden")}function b(e){const o=Math.ceil(e/H);a>=o?L.classList.remove("hidden"):l.classList.remove("hidden")}function $(){const e=u.firstElementChild;if(e){const{height:o}=e.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}function O(e){p.warning({title:"Warning",message:e,position:"topRight"})}function m(e){p.error({title:"Error",message:e,position:"topRight"})}
//# sourceMappingURL=index.js.map
