import{a as w,S as v,i as g}from"./assets/vendor-DMjJPMAs.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))r(o);new MutationObserver(o=>{for(const i of o)if(i.type==="childList")for(const n of i.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&r(n)}).observe(document,{childList:!0,subtree:!0});function s(o){const i={};return o.integrity&&(i.integrity=o.integrity),o.referrerPolicy&&(i.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?i.credentials="include":o.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function r(o){if(o.ep)return;o.ep=!0;const i=s(o);fetch(o.href,i)}})();const S="49351008-1bfee9cf32a9c846c40651839",E="https://pixabay.com/api/";async function p(e,t=1){const s={key:S,q:e,image_type:"photo",orientation:"horizontal",page:t,per_page:15,safesearch:!0},r=await w.get(E,{params:s});if(!r.data.hits.length)throw new Error("No images found");return{images:r.data.hits,totalHits:r.data.totalHits}}let l;function y(e,t){const s=e.map(q).join("");t.insertAdjacentHTML("beforeend",s),P()}setTimeout(()=>{gallery.querySelectorAll(".gallery-item").forEach(t=>t.classList.add("visible"))},50);function q({webformatURL:e,largeImageURL:t,tags:s,likes:r,views:o,comments:i,downloads:n}){return`
    <li class="gallery-item">
      <a href="${t}">
        <img src="${e}" alt="${s}" loading="lazy" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes</b>${r}</p>
        <p class="info-item"><b>Views</b>${o}</p>
        <p class="info-item"><b>Comments</b>${i}</p>
        <p class="info-item"><b>Downloads</b>${n}</p>
      </div>
    </li>
  `}function P(){l==null||l.refresh(),l=new v(".gallery a",{captionsData:"alt",captionDelay:250})}const T=document.querySelector(".form"),u=document.querySelector(".gallery"),h=document.querySelector(".loader"),c=document.querySelector(".load-more"),L=document.querySelector(".end-message");let a=1,f="";const $=15;window.addEventListener("load",()=>{h.style.display="none"});function d(e){h.style.display=e?"block":"none"}T.addEventListener("submit",async e=>{e.preventDefault();const t=e.target.elements["search-text"],s=t.value.trim();if(!s){O("Please enter a search query!");return}H(),f=s;try{d(!0);const{images:r,totalHits:o}=await p(f,a);if(!r.length){m("No images found");return}setTimeout(()=>{y(r,u),b(o)},500)}catch(r){m(r.message)}finally{setTimeout(()=>{d(!1),t.value=""},500)}});c.addEventListener("click",async()=>{a++,c.classList.add("hidden"),d(!0);try{const{images:e,totalHits:t}=await p(f,a);setTimeout(()=>{y(e,u),M(),b(t)},500)}catch(e){m(e.message)}finally{setTimeout(()=>{d(!1)},500)}});function H(){a=1,u.innerHTML="",c.classList.add("hidden"),L.classList.add("hidden")}function b(e){const t=Math.ceil(e/$);a>=t?L.classList.remove("hidden"):c.classList.remove("hidden")}function M(){const e=u.firstElementChild;if(e){const{height:t}=e.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}function O(e){g.warning({title:"Warning",message:e,position:"topRight"})}function m(e){g.error({title:"Error",message:e,position:"topRight"})}
//# sourceMappingURL=index.js.map
