import{a as b,S as w,i as g}from"./assets/vendor-DMjJPMAs.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const s of n.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&r(s)}).observe(document,{childList:!0,subtree:!0});function i(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function r(t){if(t.ep)return;t.ep=!0;const n=i(t);fetch(t.href,n)}})();const S="49351008-1bfee9cf32a9c846c40651839",v="https://pixabay.com/api/";async function p(e,o=1){const i={key:S,q:e,image_type:"photo",orientation:"horizontal",page:o,per_page:15,safesearch:!0},r=await b.get(v,{params:i});if(!r.data.hits.length)throw new Error("No images found");return{images:r.data.hits,totalHits:r.data.totalHits}}let c;function h(e,o){const i=e.map(P).join("");o.insertAdjacentHTML("beforeend",i),q()}function P({webformatURL:e,largeImageURL:o,tags:i,likes:r,views:t,comments:n,downloads:s}){return`
    <li class="gallery-item">
      <a href="${o}">
        <img src="${e}" alt="${i}" loading="lazy" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes</b>${r}</p>
        <p class="info-item"><b>Views</b>${t}</p>
        <p class="info-item"><b>Comments</b>${n}</p>
        <p class="info-item"><b>Downloads</b>${s}</p>
      </div>
    </li>
  `}function q(){c==null||c.refresh(),c=new w(".gallery a",{captionsData:"alt",captionDelay:250})}const E=document.querySelector(".form"),u=document.querySelector(".gallery"),$=document.querySelector(".loader"),l=document.querySelector(".load-more"),y=document.querySelector(".end-message");let a=1,f="";const H=15;E.addEventListener("submit",async e=>{e.preventDefault();const o=e.target.elements["search-text"],i=o.value.trim();if(!i){x("Please enter a search query!");return}M(),f=i;try{d();const{images:r,totalHits:t}=await p(f,a);if(!r.length){m("No images found");return}h(r,u),L(t)}catch(r){m(r.message)}finally{d(),o.value=""}});l.addEventListener("click",async()=>{a++,l.classList.add("hidden"),d();try{const{images:e,totalHits:o}=await p(f,a);h(e,u),O(),L(o)}catch(e){m(e.message)}finally{d()}});function M(){a=1,u.innerHTML="",l.classList.add("hidden"),y.classList.add("hidden")}function L(e){const o=Math.ceil(e/H);a>=o?y.classList.remove("hidden"):l.classList.remove("hidden")}function O(){const e=u.firstElementChild;if(e){const{height:o}=e.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}function d(){$.classList.toggle("hidden")}function x(e){g.warning({title:"Warning",message:e,position:"topRight"})}function m(e){g.error({title:"Error",message:e,position:"topRight"})}
//# sourceMappingURL=index.js.map
